name: Latest book list from goodreads
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-goodreads-books:
    name: Update README with what I'm currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          goodreads_user_id: "203298364"
          shelf: "currently-reading"
          max_books_count: "5"
          template: "- [$title]($url) by $author ($my_rating_stars)"
